PS C:\Users\Praktikant\workspace\ze> pytest
================================================================================================= test session starts ==================================================================================================
platform win32 -- Python 3.13.5, pytest-8.4.2, pluggy-1.6.0
rootdir: C:\Users\Praktikant\workspace\ze
collected 4 items / 2 errors                                                                                                                                                                                            

======================================================================================================== ERRORS ========================================================================================================
________________________________________________________________________________________ ERROR collecting tests/test_models.py _________________________________________________________________________________________ 
tests\test_models.py:10: in <module>
    test_engine = create_engine("sqlite:///:memory:")      # ін-меморі тестова база
                  ^^^^^^^^^^^^^
E   NameError: name 'create_engine' is not defined
________________________________________________________________________________________ ERROR collecting tests/test_routes.py _________________________________________________________________________________________ 
tests\test_routes.py:11: in <module>
    test_engine = create_engine("sqlite:///:memory:")      # ін-меморі тестова база
                  ^^^^^^^^^^^^^
E   NameError: name 'create_engine' is not defined
=============================================================================================== short test summary info ================================================================================================ 
ERROR tests/test_models.py - NameError: name 'create_engine' is not defined
ERROR tests/test_routes.py - NameError: name 'create_engine' is not defined
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
================================================================================================== 2 errors in 1.09s =================================================================================================== 